# Generated by Django 2.0.6 on 2018-11-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('nju_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_number2', models.CharField(default='15234721874', max_length=20, null=True)),
                ('dorm_number', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('email_address2', models.CharField(max_length=255, null=True)),
                ('grade', models.IntegerField()),
            ],
        ),
    ]
