# Generated by Django 2.0.6 on 2018-12-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
