# Generated by Django 2.0.6 on 2019-03-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_search', '0003_auto_20181204_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avator',
            field=models.CharField(default='pig.jpg', max_length=255),
        ),
    ]
