# Generated by Django 2.0.6 on 2018-11-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('session', models.CharField(max_length=255)),
                ('session_key', models.CharField(max_length=255)),
                ('openid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.IntegerField(max_length=11)),
                ('age', models.IntegerField(max_length=11)),
                ('city', models.CharField(max_length=255)),
                ('latitude', models.FloatField(max_length=11)),
                ('longitude', models.FloatField(max_length=11)),
            ],
        ),
    ]
